name: Build
on:
  workflow_dispatch:
    inputs:
      branch:
        description: branch

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  upload-sonar-results:
    name: Upload Sonar Results to Pixeebot
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'check_run' && github.event.check_run.name == 'SonarCloud Code Analysis' }}
    steps:
      - name: Upload Sonar Results
        uses: pixee/upload-tool-results-action@v1
        with:
          tool: sonar
          sonar-token: ${{ secrets.SONAR_TOKEN }}
