name: CI

on:
  push:
    branches:
      - 16Feb-ci-1

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download and install Java 17
        run: |
          curl -L https://github.com/AdoptOpenJDK/openjdk17/releases/download/jdk-17.0.5/OpenJDK17U-jdk-17.0.5-linux-x64.tar.gz -o openjdk.tar.gz
          tar -xzf openjdk.tar.gz
          export JAVA_HOME=/path/to/extracted/jdk-17.0.5
          export PATH=$JAVA_HOME/bin:$PATH

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

      - name: Analyze code with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v1.8
        with:
          args: -X
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run Snyk
        run: npx snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
