name: Semgrep

on:
  workflow_dispatch: {}

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Adjust if needed

      - name: Install semgrep-dev-autofix
        run: npm install -g semgrep-dev-autofix

      - name: Run Autofix (dry-run)
        run: semgrep-dev-autofix --dry-run

      - name: Run Autofix
        run: semgrep-dev-autofix
