name: Trivy Scan
on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t nithin246/nodejs-release2:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: 'nithin246/nodejs-release2:latest'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Fail job if Trivy scan failed
        if: steps.trivy.outcome == 'failure'
        run: |
          echo "Trivy scan found CRITICAL or HIGH vulnerabilities. Failing job."
          exit 1
